### ISSUE TITLE
Support save/load out of the box

### ISSUE THREAD

**Issue by MothDoctor** [MothCocoon/FlowGraph#10]
This puzzles me how that's possible, but I totally forgot about saving and loading the state of graphs and nodes.
It shouldn't be much work, should be addressed ASAP.

- [x] Mechanism for saving/loading active graphs and nodes
- [x] Implementing SaveGame in all nodes
- [x] Add method to Clean all the Flows before loading SaveGame during a game

**Comment by BorMor** [comment]
@MothDoctor are you planning to use ```UPROPERTY(SaveGame)``` for saving? or something different?

**Comment by MothDoctor** [comment]
> 
> 
> @MothDoctor are you planning to use `UPROPERTY(SaveGame)` for saving? or something different?

Most probably. At least, I gonna try it first :)

**Comment by MothDoctor** [comment]
Mechanism for saving/loading active graphs and nodes is ready
