### ISSUE TITLE
Only one custom input is triggered and Subgraphs can (maybe) trigger custom inputs if not active

### ISSUE THREAD

**Issue by Mephiztopheles** [MothCocoon/FlowGraph#111]
![image](https://user-images.githubusercontent.com/6481850/179549508-19cce50c-0070-40d4-a013-ec9b4096194c.png)
we wanted to create subgraphs to encapsulate actions.
Now we have different timings, when inside the subgraph something should be triggered.
This approach does not seem to work because the custom inputs won't get triggered all. Is that intended?
Is there a better way to achieve our goal?

**Comment by Mephiztopheles** [comment]
[Project.zip](https://github.com/MothCocoon/FlowGraph/files/9133555/Project.zip)

**Comment by MothDoctor** [comment]
@Mephiztopheles investigated it :)
Thanks for a nice use case there!

There was an old limitation in code allowing to execute only the first found Custom Input with the given Event Name. Removed that limitation now, so executing events should work now with randomly activated SubGraphs.

Also noticed (and fixed) debugger issue with Custom Input connections - wire coming from this node output wasn't highlighted after activating it.
![image](https://user-images.githubusercontent.com/5065057/180652838-69ddd4d7-cd39-44c5-af90-7ebb64a32bd7.png)

Small note. In your minimal project, you also got an asset error: Activity subgraph got CustomInput node with the wrong event name. Works fine after selecting a proper name.
![image](https://user-images.githubusercontent.com/5065057/180651993-da2e807b-58cb-49f0-b9ef-4c7797de78a4.png)
