### ISSUE TITLE
Wrong number of newly added output pin on Sequence node

### ISSUE THREAD

**Issue by F0bRE** [MothCocoon/FlowGraph#131]
Found this bug on the 1.3 version for UE 5.0.

If you add new output pins to the Sequence node, delete one of the pins (except last one) and then try to add new pin, the newly added pin will have wrong number. It will duplicate the number of the last pin.

For example, we add pins 2 and 3 to the Sequence node:
![image](https://user-images.githubusercontent.com/124667324/217198877-ef9636e3-a6ea-475d-a239-f22c5e51e959.png)

Remove pin 2:
![image](https://user-images.githubusercontent.com/124667324/217198991-eb85e749-7e27-431c-8fc8-f868ff0b9045.png)

Add new pin:
![image](https://user-images.githubusercontent.com/124667324/217199079-53ecd5f1-04e3-48f4-a03f-63851fa341f9.png)

When this Sequence will be executed, only one of identically named output pins will be triggered:
![image](https://user-images.githubusercontent.com/124667324/217199251-cf4b44c8-481d-421c-8de1-80d97314bdbe.png)

As far as I understood, problem is in function `void UFlowGraphNode::AddInstancePin`, in the row `const FFlowPin PinName = FFlowPin(FString::FromInt(NumberedPinsAmount));`.
It names new pin according to the number of output pins, with disregard of last pin's number.

So in my example, we have output pins 0, 1 and 3. There are three output pins, so the newly added will have PinName = 3, and we will have output pins 0, 1, 3 and 3.

**Comment by MothDoctor** [comment]
Fixed. Now pin names below removed pin should be correctly updated :)
