### ISSUE TITLE
Double-Clicks of Nodes open C++ class.

### ISSUE THREAD

**Issue by ddurwood** [MothCocoon/FlowGraph#150]
So I thought you had not implemented this but noticed it was implemented, but only working with the right-click menu, not double-clicks.

In addition, you have support for double-clicking general nodes and opening the c++ class, however, it is currently disabled in favor of the Sub Graph nodes opening up the Flow Asset they are referencing (which I agree is a great idea.)

A single click on a flow node would set the FlowAssetEditor to the correct double-click navigation state, and then the double-click would work as expected in both cases.

Was that supposed to be the intended behavior?

**Comment by MothDoctor** [comment]
> In addition, you have support for double-clicking general nodes and opening the c++ class, however, it is currently disabled in favor of the Sub Graph nodes opening up the Flow Asset they are referencing (which I agree is a great idea.)

It's not disabled. It can be changed in Editor Preferences via the `NodeDoubleClickTarget` enum :)

![image](https://user-images.githubusercontent.com/5065057/224493462-d767c559-9b49-4788-aa18-4ab1e83f6dee.png)
