### ISSUE TITLE
Play Level Sequence: "Pause at End" does nothing

### ISSUE THREAD

**Issue by soraphis** [MothCocoon/FlowGraph#155]
I guess a temporary actor is created?
And when the flow node finishes, the actor seems to be destroyed which then resets the sequence.

My setup is kinda simple:
a box is moved from A to B in a sequence. After that it should remain at B.
It works when I create a LevelSequenceActor, but not when I use the "Play Level Sequence" node.

**Comment by MothDoctor** [comment]
Should be fixed thanks to this PR :)
https://github.com/MothCocoon/FlowGraph/pull/156
