### ISSUE TITLE
RootInstances not removing flow graph when graph has finished

### ISSUE THREAD

**Issue by Variann** [MothCocoon/FlowGraph#168]
When I start a graph, finish it, then try to recreate it, the RootInstances is still referencing the owner and the flow graph inside the flow subsystem.

I'm not sure if this is intentional, but if it is, won't this lead to the owning object never getting garbage collected? Including the flow graph?

**Comment by MothDoctor** [comment]
Mhm, could you provide a detailed repo? I just checked starting and finishing Root Flow via Flow Component and it does work properly.

Asset reference had been removed from
- `RootInstances` in `UFlowSubsystem::FinishAllRootFlows`
- `InstancedTemplates` in `UFlowSubsystem::RemoveInstancedTemplate`

The latter one might not be called if you have a custom logic with calls `UFlowAsset::FinishFlow` with the optional `bRemoveInstance` parameter set to False.

**Comment by MothDoctor** [comment]
One possible edge case might be that someone managed to add Root Instance for an invalid/empty Flow Asset. I added a guard against it recently. Please try repeating issue after updating to the recent plugin version :)

**Comment by Variann** [comment]
I think I may have found the culprit. I am starting and ending the flow graph using the subsystem, not the component.
If you use `FlowSubsystem` -> `StartRootFlow`, it will add the instance to `RootInstances`
Then when the Finish node is called inside the graph, it never removes the instance from `RootInstances`.

I fixed it by calling `FinishRootFlow` from the subsystem instead of `FinishFlow` inside `FlowAsset.cpp`, but I have not tested this much to see if there are any issues doing it this way.
https://github.com/Variann/ModularityPractice/commit/3f61fe42f0c08209f582698ae4858469ef184180

The above repo that is encountering this issue. I just updated to the latest version.
To test it, undo the the changes in the above commit, then: 
1. Press play, there's a "Selected Graph" at the top left, select `FA_QuestTutorial`.
2. Press Accept or StartGraph
3. Press the B key to "drop" the quest which will call the finish node inside the graph.
4. You can not start the graph again after this and `RootInstances` is still referencing the graph, causing `CreateRootFlow` to fail.
