### ISSUE TITLE
Reroute node does not format correctly when going in reverse

### ISSUE THREAD

**Issue by Variann** [MothCocoon/FlowGraph#171]
I have a dialogue system and sometimes a dialogue option can lead to other dialogue, which loops back to the original dialogue option. But the reroute node seems to not be functioning correctly or not formatting correctly, at least when compared to the blueprint reroute node.

Current behavior:
![image](https://github.com/MothCocoon/FlowGraph/assets/6917153/c1124dac-cd5f-4615-8c2f-a9c89ef8db71)

Blueprint behavior:
![image](https://github.com/MothCocoon/FlowGraph/assets/6917153/21c754ca-2358-4183-a75f-a983d9e2b536)

**Comment by samaursa** [comment]
Just for reference, this happens even with the default way the execution wires are rendered

![image](https://github.com/MothCocoon/FlowGraph/assets/817849/6c7e58f1-bb08-4c35-9599-f78b468a98b9)

If the re-route node is not selected, then the curves 'snap' into their correct form:

![image](https://github.com/MothCocoon/FlowGraph/assets/817849/1ba8c953-392f-4045-9ab3-7f569d0291a3)
