### ISSUE TITLE
Alignment feature does not work in the FlowGraph

### ISSUE THREAD

**Issue by samaursa** [MothCocoon/FlowGraph#172]
Unreal's node alignment feature and the alignment shortcuts (`Shift+A`, `Shift+D`, `Shift+S` etc.) do not work in the NodeGraph. It would be great if this feature was added to the graph:

![image](https://github.com/MothCocoon/FlowGraph/assets/817849/c812a805-062c-4b81-8170-3c0e4414fa20)

**Comment by MothDoctor** [comment]
Feature implemented by @VintageDeveloper :)
https://github.com/MothCocoon/FlowGraph/pull/179
