### ISSUE TITLE
Add to the "Plugin Downloader"

### ISSUE THREAD

**Issue by fafato1** [MothCocoon/FlowGraph#173]
Why don't you add your plugin to a project called "Plugin downloader" is a project that helps git plugins to be easy to download

In Marketplace: https://www.unrealengine.com/marketplace/en-US/product/plugin-downloader
The plugin in github: https://github.com/Phyronnaz/PluginDownloader
The project where you add your plugin: https://github.com/Phyronnaz/PluginDownloaderData

**Comment by MothDoctor** [comment]
But it was added 3 years ago, as the 2nd plugin there? :) 
https://github.com/Phyronnaz/PluginDownloaderData/commit/3836b2c61c6951f4467cdd53f343747bce22a189
