### ISSUE TITLE
[Question] I'm curious about how you create and release versions different versions of engine all at once?

### ISSUE THREAD

**Issue by ameaninglessname** [MothCocoon/FlowGraph#198]
Did that require a customized CI pipeline or just some convenient build scripts?

**Comment by MothDoctor** [comment]
Hi, it boils down to 2 things.
- Currently, I keep all the plugin versions in the single codebase, branch called `5.x`. 
- I have a few TeamCity jobs compiling the plugin and the Flow Solo project for a few last engine versions. I run CI test after every non-trivial change, including the merge of pull requests.

Compiling the plugin itself to the "package" (a loose folder with the source code, all plugin files, plus compiled binaries) is done by a single engine job triggered this way.
`%system.RunUAT% BuildPlugin -Plugin="%teamcity.build.workingDir%\Plugins\FlowGraph\Flow.uplugin" -TargetPlatforms=Win64 -VS2022 -Package="%system.PackageFolder%%\Flow_%system.Branch%"`

After that, I just need to zip every plugin version manually.
If you'd like to discuss more, talking on Discord would be easier: https://discord.gg/Xmtr6GhbmW
