### ISSUE TITLE
Editor bug: drag pin connection

### ISSUE THREAD

**Issue by likemango** [MothCocoon/FlowGraph#203]
Hi, Here I found a bug which can crash the engine:
Hold control button and left click the pin which has any connections will crash the engine. Control button + left click is a shortcut to connect node in unreal blueprint.
Version: Flow 1.5, Unreal Engine 5.3.2
![image](https://github.com/MothCocoon/FlowGraph/assets/40531806/12adb7a1-6d37-4ad8-9425-081cbb0ee671)

**Comment by MaksymKapelianovych** [comment]
Hello. I don't think that this is a FlowGraph bug, as it can happen also in good old Blueprints. I have experienced this issue before many times, but the engine never crashed, it just continue its work.
Did Unreal engine actually crash after this exception in your case? And how often do you get this exception?

**Comment by likemango** [comment]
> Hello. I don't think that this is a FlowGraph bug, as it can happen also in good old Blueprints. I have experienced this issue before many times, but the engine never crashed, it just continue its work. Did Unreal engine actually crash after this exception in your case? And how often do you get this exception?

You are right, I'm in Debug Mode, it's just a warning log, will not crash the engine. Thanks for you reply.
