### ISSUE TITLE
The Discord Server Link in documentation no longer works

### ISSUE THREAD

**Issue by jedsallnflx** [MothCocoon/FlowGraph#218]
https://discord.gg/zMtMQ2vUUa returns an invite invalid

**Comment by cdbad** [comment]
Hey :) I would also really like to join the discord and the invite is still invalid.

**Comment by MothDoctor** [comment]
Oh, it has to be invalid for a long time... I pasted a link used on the GitHub page for years :)
Thanks for the report! :) 

![image](https://github.com/user-attachments/assets/ef349041-a06f-4764-a0b9-b9fd74deef85)
