### ISSUE TITLE
Why can't custom input trigger in subgraphs

### ISSUE THREAD

**Issue by nozomanai** [MothCocoon/FlowGraph#230]
![image](https://github.com/user-attachments/assets/ce399c39-dd91-4ea6-8fbf-caf4a0e86494)

![image](https://github.com/user-attachments/assets/4ed8beed-c8c2-4cf1-ba70-cc7f49747e48)

**111 input no Trigger, no any log, Is it my incorrect way of using it?**

**Comment by MaksymKapelianovych** [comment]
Any FlowGraph should be activated first, using Start node. CustomInput nodes can be triggered only in active Flows, but only Start node can activate Flow
