### ISSUE TITLE
[Question]I'm sorry, I'm not very good with code. I created an empty FlowGraph in an empty map with only one player, and I added a flow component and an Identity Tag to it. It should have an Identity Tag, but I still get the error "Missing Identity Tags on the Flow Component creating Flow Asset instance."

### ISSUE THREAD

**Issue by suansuansusu** [MothCocoon/FlowGraph#232]
I'm sorry, I'm not very good with code. I created an empty FlowGraph in an empty map with only one player, and I added a flow component and an Identity Tag to it. It should have an Identity Tag, but I still get the error "Missing Identity Tags on the Flow Component creating Flow Asset instance."

**Comment by MothDoctor** [comment]
Please ask this question on Discord. Community is eager to help there :) 
https://discord.gg/Xmtr6GhbmW

**Comment by suansuansusu** [comment]
Thanks a lot for your response!
