### ISSUE TITLE
Add generic UFlowRegistry that would to register custom data registry to Flow Subsystem

### ISSUE THREAD

**Issue by MothDoctor** [MothCocoon/FlowGraph#25]
It would allow using any kind of data registry without modifying the plugin :)

An excellent example would be a Fact Registry, described in my introduction video. (timestamp)
https://www.youtube.com/watch?v=Rj76JP1f-I4&t=1317s

**Comment by Drakynfly** [comment]
Could this be a thing that the new Data Registries feature of UE5 could be used for?

**Comment by MothDoctor** [comment]
Nah, nothing in common. 
This was a different idea, but I don't think anymore this is a good idea to add this to the plugin. Projects should manage on its own.
