### ISSUE TITLE
Suggestion: mention github wiki has a side panel

### ISSUE THREAD

**Issue by calicoday** [MothCocoon/FlowGraph#250]
Hi, just a small suggestion to add something like "(The Github wiki has a side panel with links to further topics.)" at the top of the Readme, wiki Home and wiki Getting Started. I was very happy to see a Concepts page but missed all the others while I tried to figure out the plugin from the source for two days. I've missed the side panel before, in other repos (Github's wiki design just doesn't work for me). I may not be the only one. 😹

**Comment by MothDoctor** [comment]
Hey, that's surprising problem you bring here ;)

I updated ReadMe part where we have wiki links. This should help.
I don't want to have these links at the top, as these new people might go to the details before reading a very short summary.
![image](https://github.com/user-attachments/assets/d8eb87ca-3602-4e94-a308-f13ce0687f67)
