### ISSUE TITLE
Flow Node Blueprint names do not appear under world in Palette after creation

### ISSUE THREAD

**Issue by Dvoya** [MothCocoon/FlowGraph#36]
Flow Node Blueprint names do not appear under world in Palette after creation, they're just empty spaces.

**Comment by MothDoctor** [comment]
@Dvoya Sorry for the wait, I accidentally turned off notifications. It's fixed now :)

Fixed my refactor, added property fallback if one of these is not set. DisplayName, Category, Description.
![UE4Editor_dV82y10Qap](https://user-images.githubusercontent.com/5065057/115902001-35206d80-a462-11eb-966c-61063af8cc88.png)
