### ISSUE TITLE
Ability to set node color per node class

### ISSUE THREAD

**Issue by darth-biomech** [MothCocoon/FlowGraph#38]
It would be nice if the node styles were customizable from the blueprints - color of the header, and other parameters if they exist.

**Comment by MothDoctor** [comment]
NodeStyle itself cannot be customized in blueprints.

However, you can already provide custom Flow Node color by implementing `GetNodeTitleColor` method. I was thinking about FLinearColor property, but I have no way of knowing if the color is set (the default black color is also valid color).
I know that directly setting color on property would be the easiest way, especially with the color picker. But I guess it's not a big issue :)
