### ISSUE TITLE
Flow module is loaded too late, resulting in FlowComponent references lost

### ISSUE THREAD

**Issue by MrBrenan** [MothCocoon/FlowGraph#39]
A fix would be to set the LoadingPhase of the Flow module to "PreDefault"
`"Modules" :
    [
        {
            "Name" : "Flow",
            "Type" : "Runtime",
            "LoadingPhase" : "PreDefault"
        },
        {
            "Name" : "FlowEditor",
            "Type" : "Editor",
            "LoadingPhase" : "Default"
        }
    ]`

**Comment by MothDoctor** [comment]
Ok, let's try this fix. I didn't spot any issues in my projects using Flow :)
