### ISSUE TITLE
Feature request: Managing flow nodes' inputs and ouputs from blueprint nodes

### ISSUE THREAD

**Issue by MrBrenan** [MothCocoon/FlowGraph#40]
I saw that you add a way to add pins in flow graph, but it'll also be very useful to manage pins at editor time.
For example for a flow node to detect specific events from the objects it's tracking and listing them as outputs.

**Comment by MothDoctor** [comment]
@MrBrenan Isn't that feature that I already implemented as "context pins"? :)

Check nodes like `UFlowNode_PlayLevelSequence` or `UFlowNode_SubGraph` that generate pins from provided assets.
