### ISSUE TITLE
[Feature request] Auto connect pins when creating a node after dragging a pin

### ISSUE THREAD

**Issue by MrBrenan** [MothCocoon/FlowGraph#45]
It's a small feature request, but i'm very used to drag connection pins, then enter the name of the node I want to use, but then the newly created node is not connected.

Here is a gif to illustrate
![CwqJ04IXWb](https://user-images.githubusercontent.com/16429096/117790961-23a0d900-b24a-11eb-8843-0d8cea4005e0.gif)

**Comment by MothDoctor** [comment]
It's already fixed by IceRivver :)
https://github.com/MothCocoon/FlowGraph/pull/43
