### ISSUE TITLE
Match type option

### ISSUE THREAD

**Issue by MrBrenan** [MothCocoon/FlowGraph#46]
The "OnNotifyFromActor" nodes matches tags with HasAnyExact, which is not always the best match type for certain situations.
A dropdown to choose the type of match (HasAnyExaxt, HasAllExact, HasAny, HasAll, etc...) in this node parameters would be very useful.

Even better would be an option in the plugin's general settings to choose the default match type.

**Comment by MothDoctor** [comment]
Hi, @MrBrenan 
Sorry for the long wait...

I implemented this request, at least partially... Not sure if you mean matching `Identity Tags` or `Notify Tags` here... Especially that some `NotifyTag` became `NotifyTags` containers at some point ;)

I exposed enum to control how these `Identity Tags` on a node should be compared with `Identity Tags` of registered components.
![image](https://user-images.githubusercontent.com/5065057/131927228-94e19989-2069-4454-bc1b-7edab0f866c8.png)

At first, I've tried to implement it for `Notify Tags`... However, it's tricky. The node receives only a single Tag at the time, so currently there's no way to check if "all Notify Tags were sent". As system doesn't remember notify tags passed previously. It just checks the tag sent with the current notify.

Let me know if I adding `Identity Match Type` was that you requested ;)

**Comment by MrBrenan** [comment]
Hi @MothDoctor !
Thanks for the update, yes I was talking about Identity Tags so it's perfect! 

Will update Flow after having a stable build for our demo, but it's great to know you still improve Flow. It is an incredible plugin, and I use it everyday.

**Comment by ameaninglessname** [comment]
By the way, there is a FGameplayTagQuery struct, which seems do the job you are taking about.

**Comment by MothDoctor** [comment]
> Will update Flow after having a stable build for our demo, but it's great to know you still improve Flow. It is an incredible plugin, and I use it everyday.

Thanks for the kind words :)

> 
> 
> By the way, there is a FGameplayTagQuery struct, which seems does the job you are taking about.
I know. I was thinking about using it, but it uses quite confusing naming, which generally isn't much human-friendly. 
Decided to follow here the rule "write code easy to understand" :)
