### ISSUE TITLE
how to support use one subgraph structure with different data

### ISSUE THREAD

**Issue by smartcyf** [MothCocoon/FlowGraph#52]
just like some tasks subgraph structure is same, but the nodes in this graph has different data (tags, float, etc..)
we want to reuse the graph, do u have some suggestions or plans to support that?

**Comment by MothDoctor** [comment]
@smartcyf 
Hi, unfortunately can't offer anything at this moment. It's possible to upgrade Flow Asset to be blueprintable and add variable support, similarly to Control Rig (mix of custom node editor and blueprints). It's a comment question and I totally understand the need for that.

However, it would take a looooot of time to implement it. No idea if I'd ever do this, sorry. Surely not this year.
