### ISSUE TITLE
Editor Crash on Flow Node BP copy & paste to another folder in the Content Browser

### ISSUE THREAD

**Issue by JimPhoenix** [MothCocoon/FlowGraph#56]
1.) Copy a Flow Node Blueprint to another folder in the Content Browser & after copied, just renamed it **while a Flow Graph is opened**:

`Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000038`

`UE4Editor_FlowEditor!UFlowGraphSchema::GetFlowNodeActions() [E:\Project Test Field\FlowGraph_427_BP\Plugins\FlowGraph_427_Precompiled\Source\FlowEditor\Private\Graph\FlowGraphSchema.cpp:215]
UE4Editor_FlowEditor!SFlowPalette::CollectAllActions() [E:\Project Test Field\FlowGraph_427_BP\Plugins\FlowGraph_427_Precompiled\Source\FlowEditor\Private\Graph\Widgets\SFlowPalette.cpp:184]
UE4Editor_FlowEditor!TBaseSPMethodDelegateInstance<0,SFlowPalette,0,void __cdecl(FGraphActionListBuilderBase &),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [G:\Epic Games\UE_4.27\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:307]
UE4Editor_GraphEditor!SGraphActionMenu::RefreshAllActions() [D:\Build\++UE4\Sync\Engine\Source\Editor\GraphEditor\Private\SGraphActionMenu.cpp:362]
UE4Editor_FlowEditor!SFlowPalette::Refresh() [E:\Project Test Field\FlowGraph_427_BP\Plugins\FlowGraph_427_Precompiled\Source\FlowEditor\Private\Graph\Widgets\SFlowPalette.cpp:154]
UE4Editor_FlowEditor!TBaseSPMethodDelegateInstance<0,SFlowPalette,0,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [G:\Epic Games\UE_4.27\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:307]
UE4Editor_FlowEditor!UFlowGraphSchema::RefreshNodeList() [E:\Project Test Field\FlowGraph_427_BP\Plugins\FlowGraph_427_Precompiled\Source\FlowEditor\Private\Graph\FlowGraphSchema.cpp:379]
UE4Editor_FlowEditor!UFlowGraphSchema::AddAsset() [E:\Project Test Field\FlowGraph_427_BP\Plugins\FlowGraph_427_Precompiled\Source\FlowEditor\Private\Graph\FlowGraphSchema.cpp:347]
UE4Editor_FlowEditor!TBaseStaticDelegateInstance<void __cdecl(FAssetData const &),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [G:\Epic Games\UE_4.27\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:731]
UE4Editor_AssetRegistry!TMulticastDelegate<void __cdecl(FAssetData const &),FDefaultDelegateUserPolicy>::Broadcast() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateSignatureImpl.inl:955]
UE4Editor_AssetRegistry!UAssetRegistryImpl::AddAssetData() [D:\Build\++UE4\Sync\Engine\Source\Runtime\AssetRegistry\Private\AssetRegistry.cpp:2658]
UE4Editor_AssetRegistry!UAssetRegistryImpl::AssetSearchDataGathered() [D:\Build\++UE4\Sync\Engine\Source\Runtime\AssetRegistry\Private\AssetRegistry.cpp:2355]
UE4Editor_AssetRegistry!UAssetRegistryImpl::ScanPathsAndFilesSynchronous() [D:\Build\++UE4\Sync\Engine\Source\Runtime\AssetRegistry\Private\AssetRegistry.cpp:2244]
UE4Editor_AssetRegistry!UAssetRegistryImpl::ScanModifiedAssetFiles() [D:\Build\++UE4\Sync\Engine\Source\Runtime\AssetRegistry\Private\AssetRegistry.cpp:3037]
UE4Editor_DataValidation!UEditorValidatorSubsystem::ValidateAllSavedPackages() [D:\Build\++UE4\Sync\Engine\Plugins\Editor\DataValidation\Source\DataValidation\Private\EditorValidatorSubsystem.cpp:402]
UE4Editor_Engine!FTimerUnifiedDelegate::Execute() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Public\TimerManager.h:51]
UE4Editor_Engine!FTimerManager::Tick() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Engine\Private\TimerManager.cpp:881]
UE4Editor_UnrealEd!UEditorEngine::Tick() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\EditorEngine.cpp:1368]
UE4Editor_UnrealEd!UUnrealEdEngine::Tick() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\UnrealEdEngine.cpp:426]
UE4Editor!FEngineLoop::Tick() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4922]
UE4Editor!GuardedMain() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:178]
UE4Editor!GuardedMainWrapper() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
UE4Editor!LaunchWindowsStartup() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:273]
UE4Editor!WinMain() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:320]
UE4Editor!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll`

2.) If you close all of the Flow Graphs and you copy a Flow Node to another folder **then you'll try to open any Flow Graph**, this will happen:

`Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000038`

`UE4Editor_FlowEditor!UFlowGraphSchema::GetFlowNodeActions() [E:\Project Test Field\FlowGraph_427_BP\Plugins\FlowGraph_427_Precompiled\Source\FlowEditor\Private\Graph\FlowGraphSchema.cpp:215]
UE4Editor_FlowEditor!SFlowPalette::CollectAllActions() [E:\Project Test Field\FlowGraph_427_BP\Plugins\FlowGraph_427_Precompiled\Source\FlowEditor\Private\Graph\Widgets\SFlowPalette.cpp:184]
UE4Editor_FlowEditor!TBaseSPMethodDelegateInstance<0,SFlowPalette,0,void __cdecl(FGraphActionListBuilderBase &),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [G:\Epic Games\UE_4.27\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:307]
UE4Editor_GraphEditor!SGraphActionMenu::RefreshAllActions() [D:\Build\++UE4\Sync\Engine\Source\Editor\GraphEditor\Private\SGraphActionMenu.cpp:362]
UE4Editor_GraphEditor!SGraphActionMenu::Construct() [D:\Build\++UE4\Sync\Engine\Source\Editor\GraphEditor\Private\SGraphActionMenu.cpp:352]
UE4Editor_FlowEditor!SFlowPalette::Construct() [E:\Project Test Field\FlowGraph_427_BP\Plugins\FlowGraph_427_Precompiled\Source\FlowEditor\Private\Graph\Widgets\SFlowPalette.cpp:106]
UE4Editor_FlowEditor!FFlowAssetEditor::CreateWidgets() [E:\Project Test Field\FlowGraph_427_BP\Plugins\FlowGraph_427_Precompiled\Source\FlowEditor\Private\Asset\FlowAssetEditor.cpp:309]
UE4Editor_FlowEditor!FFlowAssetEditor::InitFlowAssetEditor() [E:\Project Test Field\FlowGraph_427_BP\Plugins\FlowGraph_427_Precompiled\Source\FlowEditor\Private\Asset\FlowAssetEditor.cpp:189]
UE4Editor_FlowEditor!FFlowEditorModule::CreateFlowAssetEditor() [E:\Project Test Field\FlowGraph_427_BP\Plugins\FlowGraph_427_Precompiled\Source\FlowEditor\Private\FlowEditorModule.cpp:165]
UE4Editor_FlowEditor!FAssetTypeActions_FlowAsset::OpenAssetEditor() [E:\Project Test Field\FlowGraph_427_BP\Plugins\FlowGraph_427_Precompiled\Source\FlowEditor\Private\Asset\AssetTypeActions_FlowAsset.cpp:35]
UE4Editor_UnrealEd!UAssetEditorSubsystem::OpenEditorForAsset() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\Subsystems\AssetEditorSubsystem.cpp:363]
UE4Editor_UnrealEd!UAssetEditorSubsystem::OpenEditorForAssets_Advanced() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\Subsystems\AssetEditorSubsystem.cpp:437]
UE4Editor_UnrealEd!UAssetEditorSubsystem::OpenEditorForAssets() [D:\Build\++UE4\Sync\Engine\Source\Editor\UnrealEd\Private\Subsystems\AssetEditorSubsystem.cpp:553]
UE4Editor_ContentBrowserAssetDataSource!ContentBrowserAssetData::EditOrPreviewAssetFileItems() [D:\Build\++UE4\Sync\Engine\Plugins\Editor\ContentBrowser\ContentBrowserAssetDataSource\Source\ContentBrowserAssetDataSource\Private\ContentBrowserAssetDataCore.cpp:298]
UE4Editor_ContentBrowserAssetDataSource!ContentBrowserAssetData::EditOrPreviewItems() [D:\Build\++UE4\Sync\Engine\Plugins\Editor\ContentBrowser\ContentBrowserAssetDataSource\Source\ContentBrowserAssetDataSource\Private\ContentBrowserAssetDataCore.cpp:318]
UE4Editor_ContentBrowserAssetDataSource!UContentBrowserAssetDataSource::BulkEditItems() [D:\Build\++UE4\Sync\Engine\Plugins\Editor\ContentBrowser\ContentBrowserAssetDataSource\Source\ContentBrowserAssetDataSource\Private\ContentBrowserAssetDataSource.cpp:1030]
UE4Editor_ContentBrowser!SContentBrowser::OnItemsActivated() [D:\Build\++UE4\Sync\Engine\Source\Editor\ContentBrowser\Private\SContentBrowser.cpp:2281]
UE4Editor_ContentBrowser!TBaseSPMethodDelegateInstance<0,SContentBrowser,0,void __cdecl(TArrayView<FContentBrowserItem const ,int>,enum EAssetTypeActivationMethod::Type),FDefaultDelegateUserPolicy>::Execute() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:290]
UE4Editor_ContentBrowser!SAssetView::OnListMouseButtonDoubleClick() [D:\Build\++UE4\Sync\Engine\Source\Editor\ContentBrowser\Private\SAssetView.cpp:3548]
UE4Editor_ContentBrowser!TBaseSPMethodDelegateInstance<0,SAssetView,0,void __cdecl(TSharedPtr<FAssetViewItem,0>),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:307]
UE4Editor_ContentBrowser!TDelegate<void __cdecl(TSharedPtr<FAssetViewItem,0>),FDefaultDelegateUserPolicy>::ExecuteIfBound<void,0>() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateSignatureImpl.inl:599]
UE4Editor_ContentBrowser!SListView<TSharedPtr<FAssetViewItem,0> >::Private_OnItemDoubleClicked() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Public\Widgets\Views\SListView.h:1074]
UE4Editor_ContentBrowser!STableRow<TSharedPtr<FAssetViewItem,0> >::OnMouseButtonDoubleClick() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Public\Widgets\Views\STableRow.h:461]
UE4Editor_Slate!FEventRouter::Route<FReply,FEventRouter::FBubblePolicy,FPointerEvent,<lambda_2b5148752c2a272000c47b69ff14a42e> >() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:378]
UE4Editor_Slate!FSlateApplication::RoutePointerDoubleClickEvent() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5297]
UE4Editor_Slate!FSlateApplication::ProcessMouseButtonDoubleClickEvent() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5284]
UE4Editor_Slate!FSlateApplication::OnMouseDoubleClick() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5247]
UE4Editor_ApplicationCore!FWindowsApplication::ProcessDeferredMessage() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:2209]
UE4Editor_ApplicationCore!FWindowsApplication::DeferMessage() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:2698]
UE4Editor_ApplicationCore!FWindowsApplication::ProcessMessage() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:1881]
UE4Editor_ApplicationCore!FWindowsApplication::AppWndProc() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:905]
user32
user32
UE4Editor_ApplicationCore!FWindowsPlatformApplicationMisc::PumpMessages() [D:\Build\++UE4\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsPlatformApplicationMisc.cpp:125]
UE4Editor!FEngineLoop::Tick() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4851]
UE4Editor!GuardedMain() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:178]
UE4Editor!GuardedMainWrapper() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
UE4Editor!LaunchWindowsStartup() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:273]
UE4Editor!WinMain() [D:\Build\++UE4\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:320]
UE4Editor!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll`

**Comment by MothDoctor** [comment]
Crash fixed :)
