### ISSUE TITLE
Deleting Custom Blueprint FlowNode from Flowgraph Freezes Graph and Causes Crash On Save

### ISSUE THREAD

**Issue by Dvoya** [MothCocoon/FlowGraph#79]
![image](https://user-images.githubusercontent.com/60451976/146118378-5ed6b001-d9ce-4df9-9afb-571abf33a373.png)
To reproduce: Create a blueprint FlowNode of any type. Put it into a flowgraph. Then force delete the blueprint flownode. The flownode will not appear in the graphs anymore, but if you try to save, you will get this error and a crash, you will not be able to save the flowgraph.

**Comment by Dvoya** [comment]
This happens on the most current version of flowgraph-main. 4.27.2

**Comment by MothDoctor** [comment]
@Dvoya Fixed that, now Data Validation checks if node class exists. If not, it fails gracefully and only data validation fails.

![image](https://user-images.githubusercontent.com/5065057/146644315-1ec69471-d9b7-453d-8b53-084c9cf0fefa.png)
