### ISSUE TITLE
Add blackboard data in each Flowgraph asset

### ISSUE THREAD

**Issue by smartcyf** [MothCocoon/FlowGraph#82]
i have a  suggest that add blackboard data in each Flowgraph asset, so that to make the graph instance like a behavior tree, 
we could define viaribles in blackboard，and use it in each node. 
then we can use every graph by different data source

**Comment by MothDoctor** [comment]
Yeah, that would be one possible way of implementing variables in Flow Graph :)

**Comment by MothDoctor** [comment]
There are plans for implementing variable support but there's no reliable timeframe.
It's not obvious which way to choose as a proper solution for all (at least most of) the projects. It could be 
- blueprint-based variables
- blackboard-style
- blueprint-style, but using a method similar to @ryanjon2040
- also might  take inspiration from StateTree implementation in UE5

As this is a common request, I'm re-adding the task for that and closing this one.
I'll let know once we'd anything on that, so you follow the new task :)
https://github.com/MothCocoon/FlowGraph/issues/85
