### ISSUE TITLE
Add hard actor references 

### ISSUE THREAD

**Issue by Bargestt** [MothCocoon/FlowGraph#84]
I'm using multiple flow in the streamed level with multiple instances of this level.
Because of that grouping actors by tag isn't viable for me
So I've modified the asset to accept actor bindings aka LevelSequence

Any plans on implementing this? 

Here is how it looks in my project
![Screenshot 2022-01-21 182639](https://user-images.githubusercontent.com/13734283/150523256-93611719-f2f6-4632-b402-47a59dab2da8.png)
![Screenshot (5)](https://user-images.githubusercontent.com/13734283/150523263-4dffbb75-e7f5-4be7-99d1-322308779565.png)

**Comment by MothDoctor** [comment]
Hi @Bargestt 
I'm not 100% sure what is the request? If you meant "implementing variables: passing variables to nodes", it's unknown when this would implement. Especially with UObject variables.

Although @ryanjon2040 his implementation of variables on the Flow discord.

**Comment by Bargestt** [comment]
Yeah, It's passing actor variables to Flow Instance and letting nodes work with them

Although having seen mention of blackboard it would solve this problem and a bunch of others
Any plans for such? I'll probably start trying to add some form of a blackboard in a few months

**Comment by MothDoctor** [comment]
There are plans but there's no reliable timeframe.
It's not obvious which way to choose as a proper solution for all (at least most of) the projects. It could be 
- blueprint-based variables
- blackboard-style
- blueprint-style, but using a method similar to @ryanjon2040
- also might  take inspiration from StateTree implementation in UE5

As this is a common request, I'm re-adding the task for that and closing this one.
I'll let know once we'd anything on that, so you follow the new task :)
https://github.com/MothCocoon/FlowGraph/issues/85
