### ISSUE TITLE
Make possible to generate FName/FString dropdowns on blueprint function parameters without modifying the engine

### ISSUE THREAD

**Issue by MothDoctor** [MothCocoon/FlowGraph#9]
This would prevent re-typing string on blueprint functions, like the TriggerOutput method in Flow Node blueprint.

Expected result: it's possible to create customization similar to Material Parameter Collection methods, without changing core blueprint UI classes. 
![image](https://user-images.githubusercontent.com/5065057/102350702-96f93400-3fa5-11eb-8635-e9dc3a7ca97b.png)

**Comment by ameaninglessname** [comment]
Why not just use FGameplayTag instead?
It's a wrapper struct for FName and has built-in "dropdown selection" support.

**Comment by MothDoctor** [comment]
@ameaninglessname We can't use FGameplayTag customization without changing Pin Names to be gameplay tags ;)
