### ISSUE TITLE
Is Input Connected function

### ISSUE THREAD

**Issue by Vi-So** [MothCocoon/FlowGraph#96]
Would be awsome to have this same function for input.
Then we can update the node description with what is actually happening with the node.
Would be rlly valuable to the readability of the flow graph.

![Connected](https://user-images.githubusercontent.com/45290811/158642124-3e7549ee-9a90-4dce-aeb9-7780f54230cf.png)

**Comment by MothDoctor** [comment]
It's done! :)

**Comment by Vi-So** [comment]
Awsome tnx!
