### ISSUE TITLE
Add change discription backround color as option to the overidable functions

### ISSUE THREAD

**Issue by Vi-So** [MothCocoon/FlowGraph#98]
Could be really usefull to make it go red if we warn the user for an empty class for example.
If not to much of a hassle :P 

![Tip](https://user-images.githubusercontent.com/45290811/160830725-f64a674d-984e-41f4-9806-f1a78724e6ba.png)

**Comment by MothDoctor** [comment]
Actually, error coloring might be quite useful :)

**Comment by Vi-So** [comment]
Right! Thats what i wanna do with it haha.
But maybe you got some better idea's how to error color nodes ;)

**Comment by MothDoctor** [comment]
Hey @Vi-So this finally got implemented, you can add coloring logic within `GetStatusBackgroundColor` :)
