### ISSUE TITLE
"Add Pin" breaks if CanUserAddInput is enabled.

### ISSUE THREAD

**Issue by Variann** [MothCocoon/FlowGraph#99]
Steps to reproduce:
1. Create child of FlowNode (I only tested a blueprint child)
2. Override both "CanUserAddInput" and "CanUserAddOutput"
3. Have both return true.

Now when you press "Add Pin" for a output pin, it'll instead create a input pin
![Animation](https://user-images.githubusercontent.com/6917153/163736048-3ce1fa1f-e155-4075-97c5-d66e9985412f.gif)
.

**Comment by MothDoctor** [comment]
Should be fixed now :)

![image](https://user-images.githubusercontent.com/5065057/167303904-de32eebc-efe6-4657-9ef3-d2996bdf3c83.png)
